### ISSUE TITLE
Implement working with models

### ISSUE THREAD

**Issue by eumozge** [eumozge/django-queryset-gallery#4]
**Introduction**

At the moment *Gallery* method `get_page` get queryset as args. But the gallery usually works with all models objects or with the same objects as is published objects. So, it will be more convenient if *Gallery* will have const `model` and method `_get_queryset` that can be overdriven. Also, the *Gallery* must be an opportunity to get necessary queryset.

**TODO**

- [x] Add const `model`
- [x] Add method `_get_queryset`
- [x] Update method `get_page`
