### ISSUE TITLE
Get queryset with additional params

### ISSUE THREAD

**Issue by eumozge** [eumozge/django-queryset-gallery#8]
**Introduction**

There are situations when for getting queryset necessary additional params. So, the QuerySetGallery must have the opportunity to get that param. Also, sometimes it's useful to get just queryset via a gallery. 

**TODO**

- [x] Set method `_get_queryset()` as public
- [x] Add params to method `_get_queryset()`
- [x] Add `queryset_params` to method `get_page()`
